import sublime_plugin
import sublime
import re
from User.slugify import slugify

# Give a list of headings in the view. When selected,
# pack the clipboard with the link components. Actual
# link form is generated by "paste_wiki_link" as it uses
# the "anchor" file name to generate a relative link.
# kwoodham@gmail.com
# 12 Jan 2015


class LinkToHeadingCommand(sublime_plugin.TextCommand):

    def on_done(self, index):
        if index == -1:
            return

        self.view.run_command("generate_wiki_link",
            {"args": {'text': self.list[index]}})

    def run(self, edit):
        locations = self.view.find_all('^[\#]+')
        self.list = [self.view.substr(self.view.line(a)) for a in locations]
        self.view.window().show_quick_panel(self.list, self.on_done)


class GenerateWikiLink(sublime_plugin.TextCommand):

    def run(self, edit, args):
        linkName = re.sub('^[\#]+\s', '', args['text'])
        fileName = self.view.file_name()
        slugName = slugify(linkName, '-')
        outStr = linkName + '|' + fileName + '|' + slugName
        sublime.set_clipboard(outStr)
